version: '3.8'

services:
  rag-fabric-app:
    build:
      context: .
      dockerfile: Dockerfile.docker.optimized
    ports:
      - "8501:8501"
    environment:
      # Azure AD Configuration for Docker Authentication
      - AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
      - AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET}
      - AZURE_TENANT_ID=${AZURE_TENANT_ID}
      - AZURE_REDIRECT_URI=${AZURE_REDIRECT_URI:-http://localhost:8501/callback}
      - AZURE_SCOPE=${AZURE_SCOPE:-https://analysis.windows.net/powerbi/api/.default}
      
      # OpenAI Configuration
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DEFAULT_MODEL=${DEFAULT_MODEL:-gpt-3.5-turbo}
      - MAX_TOKENS=${MAX_TOKENS:-600}
      - TEMPERATURE=${TEMPERATURE:-0.2}
      
      # Authorized Users
      - AUTHORIZED_USERS=${AUTHORIZED_USERS:-mawaz@opendata.energy,jaipal@opendata.energy,vikesh@opendata.energy,sudheer@opendata.energy,selva@opendata.energy,ranjana.c@opendata.energy}
      
      # Qdrant Configuration
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - QDRANT_URL=http://qdrant:6333
      
      # Email Configuration (optional)
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      
      # Streamlit Configuration
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_SERVER_ENABLE_CORS=false
      - STREAMLIT_SERVER_ENABLE_XSRF_PROTECTION=false
      
    volumes:
      - ./logs:/app/logs
      - ./downloads:/app/downloads
      - ./models:/app/models
      - ./.env:/app/.env:ro
      
    restart: unless-stopped
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    depends_on:
      - qdrant

  # Qdrant service
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  qdrant_storage: 