# config/safe_builtins.py

# --- Safe built-ins for code execution ---
SAFE_BUILTINS = {
    "zip": zip,
    "len": len,
    "range": range,
    "min": min,
    "max": max,
    "sum": sum,
    "abs": abs,
    "sorted": sorted,
    "list": list,
    "dict": dict,
    "set": set,
    "float": float,
    "int": int,
    "str": str,
    "enumerate": enumerate,
    "any": any,
    "all": all,
    "round": round,
    "print": print,
    "type": type,
    "isinstance": isinstance,
    "bool": bool,
    "tuple": tuple,
    "reversed": reversed,
    "filter": filter,
    "map": map,
    "next": next,
    "iter": iter,
    "slice": slice,
    "object": object,
} 